services:
  - type: web
    name: lexhub
    env: node
    plan: free
    buildCommand: corepack enable && pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
